package com.example.grocerylist.entities;

import android.os.Parcel;
import android.os.Parcelable;

import com.example.grocerylist.util.MyDateFormat;

import java.util.Calendar;

/**
 *  Grocery list is the object for the main grocery list
 *  This is the parent of the Grocery list items
 */
public final class GroceryList implements Parcelable {

    private String id;
    private String listName;
    private String createDate = MyDateFormat.getDate(Calendar.getInstance());
    private String dueDate;
    private int priority;

    /**
     * empty constructor
     */
    public GroceryList() {}

    /**
     * Constructor to populate the fields
     * @param id that is generated by firebase
     * @param listName  name of the list
     * @param createDate is a string (EEE DD MMM YYYY)
     * @param dueDate   is a string (EEE DD MMM YYYY)
     * @param priority is a number of the position in the array (@arrays/gl_priority)
     */
    public GroceryList(String id, String listName, String createDate, String dueDate, int priority) {
        this.id = id;
        this.listName = listName;
        this.createDate = createDate;
        this.dueDate = dueDate;
        this.priority = priority;
    }

    /**
     * Constructor to populate the fields
     * @param listName  name of the list
     * @param dueDate   is a string (EEE DD MMM YYYY)
     * @param priority is a number of the position in the array (@arrays/gl_priority)
     */
    public GroceryList(String listName, String dueDate, int priority) {
        this.listName = listName;
        this.dueDate = dueDate;
        this.priority = priority;
    }

    /**
     * Parcelable creator
     */
    public static final Parcelable.Creator<GroceryList> CREATOR = new Parcelable.Creator<GroceryList>(){

        @Override
        public GroceryList createFromParcel(Parcel source) {
            return new GroceryList(source);
        }

        @Override
        public GroceryList[] newArray(int size) {
            return new GroceryList[0];
        }
    };

    /**
     * Constructor for the parcelable
     * @param source parcelable source
     */
    public GroceryList(Parcel source) {
        this.id = source.readString();
        this.listName = source.readString();
        this.createDate = source.readString();
        this.dueDate = source.readString();
        this.priority = source.readInt();
    }

    /**
     * Getter for the priority
     * @return priority int of the array position (@arrays/gl_priority)
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Setter for the priority
     * @param priority position in the (@arrays/gl_priority)
     */
    public void setPriority(int priority) {
        this.priority = priority;
    }

    /**
     * list id generated by firebase
     * @return id of the list
     */
    public String getId() {
        return id;
    }

    /**
     * Setter for the id
     * @param id id of the list generated by firebase
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for the list name
     * @return name of the list
     */
    public String getListName() {
        return listName;
    }

    /**
     * Setter of the list name
     * @param listName name of the list
     */
    public void setListName(String listName) {
        this.listName = listName;
    }

    /**
     * Getter of the create date
     * @return data in the string format
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * Setter of the create date
     * @param createDate in string format
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * Getter of the due date
     * @return data in the string format
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Setter of the due date
     * @param dueDate in string format
     */
    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * toString for debugging
     * @return
     */
    @Override
    public String toString() {
        return "GroceryList{" +
                "id='" + id + '\'' +
                ", listName='" + listName + '\'' +
                ", createDate='" + createDate + '\'' +
                ", dueDate='" + dueDate + '\'' +
                ", priority=" + priority +
                '}';
    }

    /**
     * describe content for the parcelable
     * note used
     * @return
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Write to the parcel
     * @param dest parcel
     * @param flags some int as flag
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.id);
        dest.writeString(this.listName);
        dest.writeString(this.createDate);
        dest.writeString(this.dueDate);
        dest.writeInt(this.priority);
    }
}
