package com.example.grocerylist.entities;

/**
 * Holds the user information
 * At the beginning it holds only the username that is Guest
 * It will be populated after the user logs in by the provided oath methods
 */
public final class User {

    private String id;
    private String name;
    private String email;
    private String image;
    private boolean isPaid;

    /**
     * Empt constructor
     */
    public User() {}

    /**
     * Constructor to populate the fields
     * @param id generated by firebase
     * @param name of the user
     * @param email of the user
     * @param image parh of the user
     * @param isPaid boolean to distinguish payed users
     */
    public User(String id, String name, String email, String image, boolean isPaid) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.image = image;
        this.isPaid = isPaid;
    }

    /**
     * Getter for the id
     * @return id of the user
     */
    public String getId() {
        return id;
    }

    /**
     * setter for the id
     * @param id string generated by firebase
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * getter for the name
     * @return name of the user
     */
    public String getName() {
        return name;
    }

    /**
     * Setter for the name
     * @param name the name of the user
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for the email
     * @return user email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Setter for the email
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for the user image
     * @return path of the image
     */
    public String getImage() {
        return image;
    }

    /**
     * Setter for the image
     * @param image the path of the image
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * Getter of the is paid user
     * @return true or false
     */
    public boolean isPaid() {
        return isPaid;
    }

    /**
     * Setter for the paid user
     * @param paid the value of the ispaid
     */
    public void setPaid(boolean paid) {
        isPaid = paid;
    }

    /**
     * toString for debugging
     * @return
     */
    @Override
    public String toString() {
        return "User{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", image='" + image + '\'' +
                ", isPaid=" + isPaid +
                '}';
    }
}
